<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "avistamiento".
 *
 * @property integer $id_avistamiento
 * @property integer $id_terreno
 * @property integer $id_taxonomia
 * @property integer $id_clima
 * @property integer $cantidad
 * @property integer $id_region
 * @property integer $id_usuario
 * @property integer $GeoN
 * @property integer $GeoE
 * @property string $Fecha
 * @property string $aliasModel
 */
abstract class Avistamiento extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'avistamiento';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_terreno', 'id_clima', 'cantidad', 'id_region', 'id_usuario', 'GeoN', 'GeoE', 'Fecha'], 'required'],
            [['id_terreno', 'id_taxonomia', 'id_clima', 'cantidad', 'id_region', 'id_usuario', 'GeoN', 'GeoE'], 'integer'],
            [['Fecha'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_avistamiento' => Yii::t('models', 'Id Avistamiento'),
            'id_terreno' => Yii::t('models', 'Id Terreno'),
            'id_taxonomia' => Yii::t('models', 'Id Taxonomia'),
            'id_clima' => Yii::t('models', 'Id Clima'),
            'cantidad' => Yii::t('models', 'Cantidad'),
            'id_region' => Yii::t('models', 'Id Region'),
            'id_usuario' => Yii::t('models', 'Id Usuario'),
            'GeoN' => Yii::t('models', 'Geo N'),
            'GeoE' => Yii::t('models', 'Geo E'),
            'Fecha' => Yii::t('models', 'Fecha'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\AvistamientoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\AvistamientoQuery(get_called_class());
    }


}
