<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "Climas".
 *
 * @property integer $id_clima
 * @property string $nom_clima
 * @property string $aliasModel
 */
abstract class Clima extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Climas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nom_clima'], 'required'],
            [['nom_clima'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_clima' => Yii::t('models', 'Id Clima'),
            'nom_clima' => Yii::t('models', 'Nom Clima'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\ClimaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\ClimaQuery(get_called_class());
    }


}
