<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "regiones".
 *
 * @property integer $id_region
 * @property string $nom_region
 * @property string $aliasModel
 */
abstract class Regione extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'regiones';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nom_region'], 'required'],
            [['nom_region'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_region' => Yii::t('models', 'Id Region'),
            'nom_region' => Yii::t('models', 'Nom Region'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\RegioneQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\RegioneQuery(get_called_class());
    }


}
