<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "Terrenos".
 *
 * @property integer $id_terreno
 * @property string $nom_terreno
 * @property integer $id_region
 * @property string $aliasModel
 */
abstract class Terreno extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Terrenos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nom_terreno', 'id_region'], 'required'],
            [['id_region'], 'integer'],
            [['nom_terreno'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_terreno' => Yii::t('models', 'Id Terreno'),
            'nom_terreno' => Yii::t('models', 'Nom Terreno'),
            'id_region' => Yii::t('models', 'Id Region'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\TerrenoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\TerrenoQuery(get_called_class());
    }


}
