<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "Usuario".
 *
 * @property integer $id_usuario
 * @property string $Usuario
 * @property integer $Contrase単a
 * @property string $Nombre
 * @property string $Apellido_M
 * @property string $Apellido_P
 * @property string $Sexo
 * @property integer $Contacto_T
 * @property string $Correo
 * @property string $Especialidad
 * @property integer $Activo
 * @property string $aliasModel
 */
abstract class Usuario extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Usuario';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Usuario', 'Contrase単a', 'Nombre', 'Apellido_M', 'Apellido_P', 'Sexo', 'Contacto_T', 'Correo', 'Especialidad', 'Activo'], 'required'],
            [['Contrase単a', 'Contacto_T', 'Activo'], 'integer'],
            [['Nombre', 'Apellido_M', 'Apellido_P', 'Correo', 'Especialidad'], 'string'],
            [['Usuario'], 'string', 'max' => 25],
            [['Sexo'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_usuario' => Yii::t('models', 'Id Usuario'),
            'Usuario' => Yii::t('models', 'Usuario'),
            'Contrase単a' => Yii::t('models', 'Contrase祓a'),
            'Nombre' => Yii::t('models', 'Nombre'),
            'Apellido_M' => Yii::t('models', 'Apellido  M'),
            'Apellido_P' => Yii::t('models', 'Apellido  P'),
            'Sexo' => Yii::t('models', 'Sexo'),
            'Contacto_T' => Yii::t('models', 'Contacto  T'),
            'Correo' => Yii::t('models', 'Correo'),
            'Especialidad' => Yii::t('models', 'Especialidad'),
            'Activo' => Yii::t('models', 'Activo'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\UsuarioQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\UsuarioQuery(get_called_class());
    }


}
