<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers\crud\base;

use backend\models\Taxonomia;
    use backend\models\search\Taxonomium as TaxonomiumSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* TaxonomiumController implements the CRUD actions for Taxonomium model.
*/
class TaxonomiumController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all Taxonomium models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new TaxonomiumSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}

/**
* Displays a single Taxonomium model.
* @param integer $Id_Taxo
*
* @return mixed
*/
public function actionView($Id_Taxo)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($Id_Taxo),
]);
}

/**
* Creates a new Taxonomium model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new Taxonomia;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'Id_Taxo' => $model->Id_Taxo]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing Taxonomium model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $Id_Taxo
* @return mixed
*/
public function actionUpdate($Id_Taxo)
{
$model = $this->findModel($Id_Taxo);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing Taxonomium model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $Id_Taxo
* @return mixed
*/
public function actionDelete($Id_Taxo)
{
try {
$this->findModel($Id_Taxo)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$Id_Taxo',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the Taxonomium model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $Id_Taxo
* @return Taxonomium the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($Id_Taxo)
{
if (($model = Taxonomia::findOne($Id_Taxo)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
