<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "Terrenos".
 *
 * @property integer $id_terreno
 * @property string $nom_terreno
 * @property integer $id_region
 * @property string $aliasModel
 */
abstract class Terrenos extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Terrenos';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nom_terreno', 'id_region'], 'required'],
            [['id_region'], 'integer'],
            [['nom_terreno'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_terreno' => 'Id Terreno',
            'nom_terreno' => 'Nom Terreno',
            'id_region' => 'Id Region',
        ];
    }

    public function getRegion(){
        return $this->hasOne(\backend\models\Regiones::className(), ['id_region'=>'id_region']);
    }




}
