<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\models\base;

use Yii;

/**
 * This is the base-model class for table "usuario".
 *
 * @property integer $id_usuario
 * @property string $Nombre
 * @property string $Apellido_M
 * @property string $Apellido_P
 * @property string $Sexo
 * @property integer $Contacto_T
 * @property string $Correo
 * @property string $Especialidad
 * @property integer $Activo
 *
 * @property \backend\models\User $usuario
 * @property string $aliasModel
 */
abstract class Usuario extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usuario';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Nombre', 'Apellido_M', 'Apellido_P', 'Sexo', 'Contacto_T', 'Correo', 'Especialidad', 'Activo'], 'required'],
            [['Nombre', 'Apellido_M', 'Apellido_P', 'Correo', 'Especialidad'], 'string'],
            [['Contacto_T', 'Activo'], 'integer'],
            [['Sexo'], 'string', 'max' => 1],
            [['id_usuario'], 'exist', 'skipOnError' => true, 'targetClass' => \backend\models\User::className(), 'targetAttribute' => ['id_usuario' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_usuario' => 'Id Usuario',
            'Nombre' => 'Nombre',
            'Apellido_M' => 'Apellido  M',
            'Apellido_P' => 'Apellido  P',
            'Sexo' => 'Sexo',
            'Contacto_T' => 'Contacto  T',
            'Correo' => 'Correo',
            'Especialidad' => 'Especialidad',
            'Activo' => 'Activo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsuario()
    {
        return $this->hasOne(\backend\models\User::className(), ['id' => 'id_usuario']);
    }




}
