<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "avistamiento".
 *
 * @property integer $id_avistamiento
 * @property integer $id_terreno
 * @property integer $id_taxonomia
 * @property integer $id_clima
 * @property integer $cantidad
 * @property integer $id_region
 * @property integer $id_usuario
 * @property integer $GeoN
 * @property integer $GeoE
 * @property string $Fecha
 * @property string $aliasModel
 */
abstract class Avistamiento extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'avistamiento';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_terreno', 'id_clima', 'cantidad', 'id_region', 'id_usuario', 'GeoN', 'GeoE', 'Fecha'], 'required'],
            [['id_terreno', 'id_taxonomia', 'id_clima', 'cantidad', 'id_region', 'id_usuario', 'GeoN', 'GeoE'], 'integer'],
            [['Fecha'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id_avistamiento' => 'Id Avistamiento',
            'id_terreno' => 'Id Terreno',
            'id_taxonomia' => 'Id Taxonomia',
            'id_clima' => 'Id Clima',
            'cantidad' => 'Cantidad',
            'id_region' => 'Id Region',
            'id_usuario' => 'Id Usuario',
            'GeoN' => 'Geo N',
            'GeoE' => 'Geo E',
            'Fecha' => 'Fecha',
        ];
    }




}
